version: '3.9'

services:
  backend-books:
    build: ./Barbara Ferlinc/book-service
    container_name: backend-books
    ports:
      - "3032:3032"
    environment:
      - DB_HOST=db-books
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-books
    networks:
      - app-network

  db-books:
    image: mongo:6.0
    container_name: db-books
    ports:
      - "27018:27017"
    volumes:
      - db_books_data:/data/db
    networks:
      - app-network

  backend-users:
    build: ./Barbara Ferlinc/user-service
    container_name: backend-users
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=db-users
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-users
    networks:
      - app-network

  db-users:
    image: mongo:6.0
    container_name: db-users
    ports:
      - "27019:27017"
    volumes:
      - db_users_data:/data/db
    networks:
      - app-network

  backend-recommendations:
    build: ./KlaraKirbis
    container_name: backend-klara
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=db-recommendations
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-recommendations
    networks:
      - app-network

  db-recommendations:
    image: mongo:6.0
    container_name: db-recommendations
    ports:
      - "27020:27017"
    volumes:
      - db_recommendations_data:/data/db
    networks:
      - app-network

  backend-notifications:
    build: ./VivienStampfer/notifications
    container_name: backend-vivi
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db-notifications
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-notifications
    networks:
      - app-network

  db-notifications:
    image: mongo:6.0
    container_name: db-notifications
    ports:
      - "27021:27017"
    volumes:
      - db_notifications_data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BOOKS_API_URL=http://backend-books:3032
      - USERS_API_URL=http://backend-users:3030
      - RECOMMENDATIONS_API_URL=http://backend-klara:3003
      - NOTIFICATIONS_API_URL=http://backend-vivi:3001
    depends_on:
      - backend-books
      - backend-users
      - backend-klara
      - backend-vivi
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_books_data:
  db_users_data:
  db_recommendations_data:
  db_notifications_data:
