version: '3.9'

services:
  backend-books:
    build: "./BarbaraFerlinc/book-service"
    container_name: backend-books
    ports:
      - "3032:3032"
    environment:
      - DB_HOST=db-books
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-books
    networks:
      - app-network

  db-books:
    image: mongo:6.0
    container_name: db-books
    ports:
      - "27018:27017"
    volumes:
      - db_books_data:/data/db
    networks:
      - app-network

  backend-users:
    build: "./BarbaraFerlinc/user-service"
    container_name: backend-users
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=db-users
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-users
    networks:
      - app-network

  db-users:
    image: mongo:6.0
    container_name: db-users
    ports:
      - "27019:27017"
    volumes:
      - db_users_data:/data/db
    networks:
      - app-network

  backend-recommendations:
    build: "KlaraKirbis/recommendation-service"
    container_name: backend-recommendations
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=db-recommendations
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-recommendations
    networks:
      - app-network

  db-recommendations:
    image: mongo:6.0
    container_name: db-recommendations
    ports:
      - "27020:27017"
    volumes:
      - db_recommendations_data:/data/db
    networks:
      - app-network

  backend-notifications:
    build: "./VivienStampfer/notifications"
    container_name: backend-notifications
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db-notifications
      - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - db-notifications
    networks:
      - app-network

  db-notifications:
    image: mongo:6.0
    container_name: db-notifications
    ports:
      - "27021:27017"
    volumes:
      - db_notifications_data:/data/db
    networks:
      - app-network

  db-reviews:
    image: mongo:6.0.14-jammy
    command: ["mongod", "--bind_ip_all"]
    restart: unless-stopped
    volumes:
      - db_reviews_data:/data/db
    # healthcheck:
    #   test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017", "--eval", "db.adminCommand({ ping: 1 })"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 30
    networks:
      - app-network

  backend-reviews:
    build: "./LenaBojc/review-service"
    environment:
      MONGO_URL: "mongodb://db-reviews:27017"
      DB_NAME: "booknest_reviews"
      FRONTEND_URL: "http://frontend:3000"
      USERS_API_URL: "http://backend-users:3030"
      BOOKS_API_URL: "http://backend-books:3032"
      RECOMMENDATIONS_API_URL: "http://backend-recommendations:3003"
      NOTIFICATIONS_API_URL: "http://backend-notifications:3001"
    ports:
      - "3002:3002"
    depends_on:
      - db-reviews
        # condition: service_healthy
    networks: 
      - app-network

  frontend:
    build: "./frontend"
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BOOKS_API_URL=http://backend-books:3032
      - USERS_API_URL=http://backend-users:3030
      - RECOMMENDATIONS_API_URL=http://backend-recommendations:3003
      - NOTIFICATIONS_API_URL=http://backend-notifications:3001
      - REVIEWS_API_URL=http://backend-reviews:3002
    depends_on:
      - backend-books
      - backend-users
      - backend-recommendations
      - backend-notifications
      - backend-reviews
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_books_data:
  db_users_data:
  db_recommendations_data:
  db_notifications_data:
  db_reviews_data:
