version: '3.9'

services:
  backend-books:
    build: "./BarbaraFerlinc/book-service"
    container_name: backend-books
    ports:
      - "3032:3032"
    env_file:
      - ./BarbaraFerlinc/book-service/.env
    environment:
      # - DB_HOST=db-books
      # - DB_PORT=27017
      FRONTEND_URL: http://frontend:3000
      REVIEWS_API_URL: http://backend-reviews:3002
      CONTENT_NOTICES_URL: https://contentnotices.onrender.com/v1/content-notices
      BOOK_BADGES_URL: https://book-badges.vercel.app/api/book-badges
    # depends_on:
    #   - db-books
    networks:
      - app-network

  backend-users:
    build: "./BarbaraFerlinc/user-service"
    container_name: backend-users
    ports:
      - "3030:3030"
    env_file:
      - ./BarbaraFerlinc/user-service/.env
    environment:
      # - DB_HOST=db-users
      # - DB_PORT=27017
      FRONTEND_URL: http://frontend:3000
      STATISTICS_API_URL: http://backend-statistics:3004
    # depends_on:
    #   - db-users
    networks:
      - app-network

  backend-recommendations:
    build: "KlaraKirbis/recommendation-service"
    container_name: backend-recommendations
    ports:
      - "3003:3003"
    env_file:
      - ./KlaraKirbis/recommendation-service/.env
    environment:
      # - DB_HOST=db-recommendations
      # - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
    # depends_on:
    #   - db-recommendations
    networks:
      - app-network

  backend-notifications:
    build: "./VivienStampfer/notifications"
    container_name: backend-notifications
    ports:
      - "3001:3001"
    env_file:
      - ./VivienStampfer/notifications/.env
    environment:
      # - DB_HOST=db-notifications
      # - DB_PORT=27017
      - FRONTEND_URL=http://frontend:3000
      - STATISTICS_API_URL=http://backend-statistics:3004
    # depends_on:
    #   - db-notifications
    networks:
      - app-network

  backend-reviews:
    build: "./LenaBojc/review-service"
    container_name: backend-reviews
    ports:
      - "3002:3002"
    env_file:
      - ./LenaBojc/review-service/.env
    environment:
      FRONTEND_URL: "http://frontend:3000"
      # USERS_API_URL: "http://backend-users:3030"
      BOOKS_API_URL: "http://backend-books:3032"
    networks: 
      - app-network

  backend-statistics:
    build: "./LenaBojc/statistics-service"
    container_name: backend-statistics
    ports:
      - "3004:3004"
    env_file:
      - ./LenaBojc/statistics-service/.env
    environment:
      FRONTEND_URL: http://frontend:3000
      SHELVES_API_URL: http://backend-shelves:3005
    networks:
      - app-network

  backend-shelves:
    build: "./VivienStampfer/shelves"
    container_name: backend-shelves
    ports:
      - "3005:3005"
    env_file:
      - ./VivienStampfer/shelves/.env
    environment:
      - FRONTEND_URL=http://frontend:3000
      - BOOKS_API_URL=http://backend-books:3032
    networks:
      - app-network

  frontend:
    build: "./frontend"
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - BOOKS_API_URL=http://backend-books:3032
      - USERS_API_URL=http://backend-users:3030
      - RECOMMENDATIONS_API_URL=http://backend-recommendations:3003
      - NOTIFICATIONS_API_URL=http://backend-notifications:3001
      - REVIEWS_API_URL=http://backend-reviews:3002
      - STATISTICS_API_URL=http://backend-statistics:3004
      - SHELVES_API_URL=http://backend-shelves:3005
    depends_on:
      - backend-books
      - backend-users
      - backend-recommendations
      - backend-notifications
      - backend-reviews
      - backend-statistics
      - backend-shelves
    networks:
      - app-network

networks:
  app-network:
