version: '3.9'

services:
  recommendations-service:
    build: ./recommendations-service
    container_name: recommendations-service
    restart: always
    ports:
      - "3003:5005"
    environment:
      - MONGO_URI=env.MONGODB_URI
      - PORT=3003
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
